version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:sdk-tag-1.37.19-64bit
    steps:
      - checkout
      - run: git submodule update --init
      - run: |
          . /entrypoint
          echo $PATH
          scripts/travis-emscripten/install_deps.sh
      - run: |
          . /entrypoint
          scripts/travis-emscripten/build_emscripten.sh